### ISSUE TITLE
Adding Animation

### ISSUE THREAD

**Issue by dot-ly** [francoiscampbell/CircleLayout#4]
How would I got about adding an animation to this layout? I want the children to animate out from the center. 

Thanks,

Ahmed

**Comment by francoiscampbell** [comment]
Good idea. I've started work on that in the `animation` branch. Ill let you know when it's done.

**Comment by dot-ly** [comment]
I got something working for Xamarin....i'll post the code here later on.

**Comment by francoiscampbell** [comment]
Done in v0.3.0
