### ISSUE TITLE
Spinning CircleLayout

### ISSUE THREAD

**Issue by JoaoFilhoG3** [francoiscampbell/CircleLayout#7]
Is there a way to make the CircleLayout spin?

**Comment by francoiscampbell** [comment]
You can animate the `angleOffset` property using `ObjectAnimator`: https://developer.android.com/guide/topics/graphics/prop-animation.html#object-animator

It might look like:
```java
ObjectAnimator animation = ObjectAnimator.ofFloat(circleLayout, "angleOffset", 90f);
animation.setDuration(1000);
animation.start();
```
or in Kotlin:
```kotlin
val animation = ObjectAnimator.ofFloat(circleLayout, "angleOffset", 90f).apply {
    setDuration(1000);
    start();
}
```
I haven't run this, let me know if it works

**Comment by JoaoFilhoG3** [comment]
It works, thank you
